### ISSUE TITLE
Cannot download pysysp by pip

### ISSUE THREAD

**Issue by Firestar-Reimu** [mdusilva/pysysp#2]
The error is:
```
ImportError: cannot import name '_get_unpatched' from 'setuptools.dist' (/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py). Did you mean: 'get_unpatched'?
            [end of output]
```

Full output:
```bash
(base) [firestar @ Archlinux ~] (16:55:44)
$ pip install pysysp
Collecting pysysp
  Using cached pysysp-1.0.1.zip (169 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/firestar/.miniconda/lib/python3.12/site-packages (from pysysp) (1.26.4)
Collecting pyfits (from pysysp)
  Using cached pyfits-3.5.tar.gz (1.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [280 lines of output]
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'author-email' will not be supported in future
              versions. Please use the underscore name 'author_email' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'home-page' will not be supported in future
              versions. Please use the underscore name 'home_page' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'requires-python' will not be supported in future
              versions. Please use the underscore name 'requires_python' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'requires-dist' will not be supported in future
              versions. Please use the underscore name 'requires_dist' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'pre-hook.numpy-extension-hook' will not be supported in future
              versions. Please use the underscore name 'pre_hook.numpy_extension_hook' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'upload-dir' will not be supported in future
              versions. Please use the underscore name 'upload_dir' instead.
      
              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [109 lines of output]
            /tmp/pip-wheel-lf2_lg43/stsci-distutils_64b4606c3d8a495fb4e72f8d0a8b2f6d/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
              from pkg_resources import get_distribution, Requirement
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
            !!
      
                    ********************************************************************************
                    Usage of dash-separated 'author-email' will not be supported in future
                    versions. Please use the underscore name 'author_email' instead.
      
                    By 2024-Sep-26, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              opt = self.warn_dash_deprecation(opt, section)
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
            !!
      
                    ********************************************************************************
                    Usage of dash-separated 'home-page' will not be supported in future
                    versions. Please use the underscore name 'home_page' instead.
      
                    By 2024-Sep-26, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              opt = self.warn_dash_deprecation(opt, section)
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
            !!
      
                    ********************************************************************************
                    Usage of dash-separated 'description-file' will not be supported in future
                    versions. Please use the underscore name 'description_file' instead.
      
                    By 2024-Sep-26, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              opt = self.warn_dash_deprecation(opt, section)
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
            !!
      
                    ********************************************************************************
                    Usage of dash-separated 'requires-python' will not be supported in future
                    versions. Please use the underscore name 'requires_python' instead.
      
                    By 2024-Sep-26, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              opt = self.warn_dash_deprecation(opt, section)
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py:478: SetuptoolsDeprecationWarning: Invalid dash-separated options
            !!
      
                    ********************************************************************************
                    Usage of dash-separated 'requires-dist' will not be supported in future
                    versions. Please use the underscore name 'requires_dist' instead.
      
                    By 2024-Sep-26, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              opt = self.warn_dash_deprecation(opt, section)
            /home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
            !!
      
                    ********************************************************************************
                    Requirements should be satisfied by a PEP 517 installer.
                    If you are using pip, you can try `pip install --use-pep517`.
                    ********************************************************************************
      
            !!
              dist.fetch_build_eggs(dist.setup_requires)
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-wheel-lf2_lg43/stsci-distutils_64b4606c3d8a495fb4e72f8d0a8b2f6d/setup.py", line 80, in <module>
                setup(
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 146, in setup
                _setup_distribution = dist = klass(attrs)
                                             ^^^^^^^^^^^^
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py", line 309, in __init__
                _Distribution.__init__(self, dist_attrs)
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
                self.finalize_options()
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py", line 661, in finalize_options
                ep(self)
              File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py", line 681, in _finalize_setup_keywords
                ep.load()(self, ep.name, value)
              File "/tmp/pip-wheel-lf2_lg43/stsci-distutils_64b4606c3d8a495fb4e72f8d0a8b2f6d/.eggs/d2to1-0.2.12.post1-py3.12.egg/d2to1/core.py", line 30, in d2to1
                from setuptools.dist import _get_unpatched
            ImportError: cannot import name '_get_unpatched' from 'setuptools.dist' (/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py). Did you mean: 'get_unpatched'?
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home/firestar/.miniconda/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/firestar/.miniconda/bin/python3.12', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6u8orwjr', '--quiet', 'stsci.distutils>=0.3']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-lkpbh7y4/pyfits_7fe6dfefc41d4eb2a70b43bd34bc2d05/setup.py", line 11, in <module>
          setup(
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/dist.py", line 643, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/pkg_resources/__init__.py", line 889, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/pkg_resources/__init__.py", line 925, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1256, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1292, in obtain
          return installer(requirement) if installer else None
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/firestar/.miniconda/lib/python3.12/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/firestar/.miniconda/bin/python3.12', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6u8orwjr', '--quiet', 'stsci.distutils>=0.3']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by mdusilva** [comment]
I'd uploaded a new version compatible with Python3.
